name: CI - PR Tests

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkstyle with Gradle
      run: ./gradlew checkstyle
    - name: Lint with Gradle
      run: ./gradlew lint
